---
# tasks file for fluentd-windows
- name: Install agent
  win_package:
    path: "{{ __fluentd_distr_msi }}"
    product_id: '{C6699D5E-8ED4-4359-A97E-B88F24B083EF}'
    state: present

- name: Register installed plugins
  win_command: "{{ __fluentd_gem_bin }} list"
  register: gem_list
  changed_when: False

- name: copy fluentd conf
  template:
    src: td-agent.j2
    dest: C:\opt\td-agent\etc\td-agent\td-agent.conf
  notify: restart fluentd

- name: Install fluent plugins
  win_command: "{{ __fluentd_gem_bin }} install {{ item }}"
  with_items: "{{ __fluentd_gem_gelf }}"
  when: not ( gem_list.stdout | regex_search(item) )
  notify: restart fluentd